version: '3.3'

services:
   db:
     image: michelleblond/scrabbledb
     restart: always

   phpadmin:
     depends_on:
       - db
     image: michelleblond/nodescrabbletrainer 
     ports:
       - "80:8080"
     restart: always
     links:
       - db
volumes:
    db_data: {}